language: php
php:
- 7.4.33

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer exec strukt-cfg
  - php console app:make Payroll
  - php console app:reload

script: phpunit
